### ISSUE TITLE
Acquire data from Core Logic

### ISSUE THREAD

**Issue by sewardlee337** [sfbrigade/datasci-firerisk#6]
Currently seeking high-quality data related to fire and other natural hazards from [Core Logic](http://www.corelogic.com/).

This dataset will have more details than what we can get publicly, including:
* Fire hydrant location
* Distance from fire station in relation to coverage area
* Building construction materials (??)

Proposed (max) budget for proprietary datasets: $2,000

**Comment by ryangtanaka-org** [comment]
Small update -- I gave CoreLogic our project scope and budget, but we might be too underfunded for this for them to consider us a real client.  (They were pretty clear about the fact that their service is "expensive", at least.)

I'll wait a little while longer in the off chance they get back to me, but I don't think we should count on this data set coming through for now.

**Comment by sewardlee337** [comment]
@rtanaka1981 recommend that you close this issue if you think we are very unlikely to get the the Core Logic data.

**Comment by ryangtanaka-org** [comment]
Yeah, I'll wait for one more week and see where it goes, but otherwise I'll close it afterwards, I think.
